artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.usercontent.google.com/u/0/uc?id=1WTSoktGIVNhHhsZX9i-iBTA2CM_8EP1E&export=download
  local_data_file: artifacts/data_ingestion/raw_data.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/raw_data.csv
  clean_data_file: artifacts/data_preprocessing/clean_data.csv

data_preparation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_preprocessing/clean_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preparation/
  stores_list_file: artifacts/data_preprocessing/stores.pkl
  preprocessor_file: artifacts/data_transformation/preprocessor.pkl

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/
  model_path: artifacts/model_trainer/model.pkl
  metrics_file_name: artifacts/model_evaluation/metrics.csv